# Add inside src/levels/united_center_4d.gd under the _ready() logic block

func configure_jumbotron_shader_links(director_ref: Marker3D) -> void:
	var feed = $Jumbotron/JumbotronFeed as JumbotronFeed
	feed.match_director = director_ref
	
	# Extract the dynamic texture surface generated by the SubViewport
	var texture_render_target = feed.get_texture()
	
	# Apply the viewport texture directly into the mesh's material parameters
	var screen_mesh: MeshInstance3D = $Jumbotron/ScreenMesh
	var material = screen_mesh.get_active_material(0) as ShaderMaterial
	
	if material:
		material.set_shader_parameter("viewport_texture", texture_render_target)
